# Auto-generated by release workflow. Do not edit.
#
# Usage:
#   Latest:  import ./default.nix { inherit pkgs; }
#   Pinned:  import ./default.nix { inherit pkgs; release = ./releases/v0.10.9-nix.1.nix; }
{
  pkgs,
  release ? ./releases/0.11.27.nix,
}:

let
  lib = pkgs.lib;
  system = pkgs.stdenv.hostPlatform.system;

  resolve = attr:
    lib.getAttrFromPath (lib.splitString "." attr) pkgs;

  meta = import release;
  asset = meta.assets.${system} or null;

  sharedLibs = [
    (resolve "zlib")
    (resolve "libffi")
    (resolve "bzip2")
    (resolve "xz")
    (resolve "ncurses")
    (resolve "readline")
    (resolve "openssl")
    (resolve "sqlite")
    (resolve "expat")
  ];

  linuxLibs = [
    (resolve "glibc")
    (resolve "stdenv.cc.cc.lib")
    (resolve "util-linux.out")
  ];

  darwinLibs = [
    (resolve "libiconv")
  ];

  buildInputs = sharedLibs
    ++ (if pkgs.stdenv.isLinux then linuxLibs else darwinLibs)
    ++ [ pkgs.rust-jemalloc-sys ]
    ++ lib.optionals pkgs.stdenv.isLinux [ pkgs.stdenv.cc.cc.lib ];

in if asset == null then null
else pkgs.stdenv.mkDerivation {
  pname = "uv-nix-bin";
  inherit (meta) version;
  inherit buildInputs;

  src = builtins.fetchurl {
    inherit (asset) url;
    sha256 = asset.hash;
  };

  dontUnpack = true;

  nativeBuildInputs = lib.optionals pkgs.stdenv.isLinux [
    pkgs.autoPatchelfHook
  ];

  installPhase = ''
    runHook preInstall
    install -Dm755 $src $out/bin/uv
    runHook postInstall
  '';

  meta = {
    description = "uv Python package manager with Nix integration (pre-built)";
    homepage = "https://github.com/chadac/uv-nix";
    mainProgram = "uv";
  };
}
