# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.17-nix";
  tag = "0.11.17";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.17/uv-nix-0.11.17-linux-x86_64";
      hash = "sha256-nKjEu5ZBjRJUXTmPUu4ZINVnEiE2HXTZPKPzi3+yVpI=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.17/uv-nix-0.11.17-linux-aarch64";
      hash = "sha256-/VOOjVC3ofN2IHnhu373Euad/oqyjdsX0S2GYmBKOL0=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.17/uv-nix-0.11.17-darwin-arm64";
      hash = "sha256-ycDy9E+Sr0UzO+HticfaBWaLGIauklEldgpah1aJh3U=";
    };
  };
}
