# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.19-nix";
  tag = "0.11.19";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.19/uv-nix-0.11.19-linux-x86_64";
      hash = "sha256-R86Y0Ps+qz6uTv0sxpyez4t9+jGvThCPxQFtwvWahAY=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.19/uv-nix-0.11.19-linux-aarch64";
      hash = "sha256-OCYLV/09bhL4juVNNLbkd53cnKQbpDE7jBCuherA2f0=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.19/uv-nix-0.11.19-darwin-arm64";
      hash = "sha256-9BMfbSUHgJNJI3aOHb+zKzXh6YOFUsQji4MyfQR2wLE=";
    };
  };
}
