# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.30-nix";
  tag = "0.11.30";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.30/uv-nix-0.11.30-linux-x86_64";
      hash = "sha256-tN0OobsmxAAIjtGDt4bCXvijk1IrSKwKxLOVj/CV9XI=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.30/uv-nix-0.11.30-linux-aarch64";
      hash = "sha256-ORGw0a8p99GT0xm6cMYTeHBD+TL68cXkl2v4sJVbxBQ=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.30/uv-nix-0.11.30-darwin-arm64";
      hash = "sha256-kWo7FVs1irpwur92xvxOjsM/eHt/cPynuPPxvsAWOr0=";
    };
  };
}
