# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.25-nix";
  tag = "0.11.25";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.25/uv-nix-0.11.25-linux-x86_64";
      hash = "sha256-ezn4DBFyWC2wT4Io6EeCUFwdlTLbKFEm94xpoY3fyHQ=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.25/uv-nix-0.11.25-linux-aarch64";
      hash = "sha256-XbgvGl1+F5Ygm1ur2ruxkQ48sIMWSoP7XZY/j+BDFiM=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.25/uv-nix-0.11.25-darwin-arm64";
      hash = "sha256-lqKKjJvESOi1Hy3EcB+y+9XuVdcP8vwvQy3EweAYzrY=";
    };
  };
}
