# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.32-nix";
  tag = "0.11.32";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.32/uv-nix-0.11.32-linux-x86_64";
      hash = "sha256-abxHqQzvJvI/22pvDQrJeFpiIJhGS82gIZ046ToOr7k=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.32/uv-nix-0.11.32-linux-aarch64";
      hash = "sha256-UMAYA1GjwuTfldmd9VC29C8HaEDwlD40fZj0mZOzC44=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.32/uv-nix-0.11.32-darwin-arm64";
      hash = "sha256-Lrn/YKejOUfpNTP94DTr6FD+sR/7qhw8Ul0u2O2JmmU=";
    };
  };
}
