# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.28-nix";
  tag = "0.11.28";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.28/uv-nix-0.11.28-linux-x86_64";
      hash = "sha256-P0KrsLpOSrVpssL/G+a1Cc29LjRZvBT+USb0HMSexEQ=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.28/uv-nix-0.11.28-linux-aarch64";
      hash = "sha256-6bjJlNIANapJJV8TlY9h4518FXu5n2z84vmkCBLthms=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.28/uv-nix-0.11.28-darwin-arm64";
      hash = "sha256-To/cMWgvcp1jwJOW1Hr2hF8Jm06LSfGwNfy6kNEfNDs=";
    };
  };
}
