# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.27-nix";
  tag = "0.11.27";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.27/uv-nix-0.11.27-linux-x86_64";
      hash = "sha256-dqliHlSTYdSUlFNnGnb52B0EJFqJRF2O5qtn3PvbGlA=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.27/uv-nix-0.11.27-linux-aarch64";
      hash = "sha256-2iLqE1ze4aLV/+bH9j5v1YPi5YGJVvJcMPjhCY5GCS8=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.27/uv-nix-0.11.27-darwin-arm64";
      hash = "sha256-kkpRk2YL0kUFjNKSNDgh+DlpKaGVrh5BeU1TI4uyogY=";
    };
  };
}
