# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.21-nix";
  tag = "0.11.21";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.21/uv-nix-0.11.21-linux-x86_64";
      hash = "sha256-cph/CjxIwhhOdQPdRx/JDm3pSIhMTtLz4MNyXcQJGDE=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.21/uv-nix-0.11.21-linux-aarch64";
      hash = "sha256-ngBIrBBsn3Hz/BUoemGzYonXapXCiJRgpeLoo3i224M=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.21/uv-nix-0.11.21-darwin-arm64";
      hash = "sha256-yNbUjy04BjZxvLT7e5nWJiJDQxs5zfQ9bIG4ulzYio4=";
    };
  };
}
