# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.22-nix";
  tag = "0.11.22";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.22/uv-nix-0.11.22-linux-x86_64";
      hash = "sha256-gY8pdxCyPyXqaRm3SWE6hUKSluXRdl0CeM+P/c92JCM=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.22/uv-nix-0.11.22-linux-aarch64";
      hash = "sha256-6p8QGeF4KtCxeoS7pOhrQ0PcmWCS5baQoj2TkzlSG2o=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.22/uv-nix-0.11.22-darwin-arm64";
      hash = "sha256-6Bj11PzJX57g7Us9tGglS2Agvo5yLKtY/QSv5gHsb04=";
    };
  };
}
