# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.31-nix";
  tag = "0.11.31";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.31/uv-nix-0.11.31-linux-x86_64";
      hash = "sha256-GUiW2QcjxZ3fE1oHs0moBQHW2cJHlmgueXhdV/7Uag4=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.31/uv-nix-0.11.31-linux-aarch64";
      hash = "sha256-6v+QMAH7XCTYzt3SZa7qjUMIDd8UFEvVmVOrF3PsAy8=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.31/uv-nix-0.11.31-darwin-arm64";
      hash = "sha256-gpPki0GSAjA5DlFq0/F9rQKar/BzEp3+1uBj0f8NNI8=";
    };
  };
}
