# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.24-nix";
  tag = "0.11.24";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.24/uv-nix-0.11.24-linux-x86_64";
      hash = "sha256-HkFp4q7s8HWZ/l5jpn5xKkJ+UvWPAu2UWYQzjxfnXuo=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.24/uv-nix-0.11.24-linux-aarch64";
      hash = "sha256-JcGx/UpfMIpbUqBUICrCnHnhdUr+z+L6cPJFq6vAhRM=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.24/uv-nix-0.11.24-darwin-arm64";
      hash = "sha256-aYTgaxn7s5P5EC8QBav+VguO/FfcLY3AmyXpiZwrW3Y=";
    };
  };
}
