# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.33-nix";
  tag = "0.11.33";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.33/uv-nix-0.11.33-linux-x86_64";
      hash = "sha256-zxk0poyeUAvbnLwHZNgF/s2AGq8Zn73YXx5S320jN3Q=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.33/uv-nix-0.11.33-linux-aarch64";
      hash = "sha256-BY6/5M5bixM5n6WmLy89/ru9AREOq305EcBZD5qaEio=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.33/uv-nix-0.11.33-darwin-arm64";
      hash = "sha256-7Vgf8qgF6Bjq/PkApJ9Rm6W2UCxcDPKThwh4wC999bk=";
    };
  };
}
