# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.26-nix";
  tag = "0.11.26";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.26/uv-nix-0.11.26-linux-x86_64";
      hash = "sha256-FqRElpxLtgvVL+G/DW9TbH4cUOmfqnDR+HFE6N0R91A=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.26/uv-nix-0.11.26-linux-aarch64";
      hash = "sha256-M9avftJ9kLkwk2QdHl4xVKTPz8n8WYjgWErSKVN34vU=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.26/uv-nix-0.11.26-darwin-arm64";
      hash = "sha256-eVP/1wDzlEgIxQK0n//7g3s/ds7F+CEuT4Jb19jUKP0=";
    };
  };
}
