# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.23-nix";
  tag = "0.11.23";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.23/uv-nix-0.11.23-linux-x86_64";
      hash = "sha256-zECDLn2MpUylARR6+c8sT5cFEDx+M+uUO5B0AQWiPXE=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.23/uv-nix-0.11.23-linux-aarch64";
      hash = "sha256-F6GZql1SqTikhuOMTXfw2qgd8mHUmNF8LbOv7+ydWuY=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.23/uv-nix-0.11.23-darwin-arm64";
      hash = "sha256-0Mtjq076ixpX3p6bpi9UqnNHXKlG3yoxsiOfyxF5Ixo=";
    };
  };
}
