# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.29-nix";
  tag = "0.11.29";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.29/uv-nix-0.11.29-linux-x86_64";
      hash = "sha256-5ROIKOpnEqxXYssggWTrJrEhViO6BFzwrbhDxuD0BZI=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.29/uv-nix-0.11.29-linux-aarch64";
      hash = "sha256-3i2D/tsGrM6sA8ghoY2vyUd7qm/6cXsHNJOxqGLFAJo=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.29/uv-nix-0.11.29-darwin-arm64";
      hash = "sha256-VIzc/Q9wNQh61Zev2ddW7mtbiCFfmIr3j1hNs3+L9CU=";
    };
  };
}
