# Auto-generated by release workflow. Do not edit.
{
  version = "0.11.20-nix";
  tag = "0.11.20";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.20/uv-nix-0.11.20-linux-x86_64";
      hash = "sha256-L9ynHwTuvURvhaaaZoOAowxfia4yNvV4ZKnrkddMNMY=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.20/uv-nix-0.11.20-linux-aarch64";
      hash = "sha256-e0JTLbwR9HaNCdTH8KXbPy9SJTD4J7PcJy3fPxIgdds=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.11.20/uv-nix-0.11.20-darwin-arm64";
      hash = "sha256-TsuLd7dCrbbtjGKf/N2HzzU1PdAHkq1EPbfcTAUbD+w=";
    };
  };
}
