# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.21-nix";
  tag = "0.12.21";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.21/uv-nix-0.12.21-linux-x86_64";
      hash = "sha256-E6DBnlJmMXotoJBFMVP46ARR2mPpoI4TWj/PEyw88JE=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.21/uv-nix-0.12.21-linux-aarch64";
      hash = "sha256-Ey3L0jApjTxzqV1qJFOsCJMdcdIxFWN5gAFznIQbuKI=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.21/uv-nix-0.12.21-darwin-arm64";
      hash = "sha256-BqeLyU7TCISNUFQEYRZ5ZiJ8zTPgjCnkTgd2Kx94Nxk=";
    };
  };
}
