# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.19-nix";
  tag = "0.12.19";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.19/uv-nix-0.12.19-linux-x86_64";
      hash = "sha256-DYhvkiEKVirAAnRbK7mU8ECijynFPffRxLbEBT7yotc=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.19/uv-nix-0.12.19-linux-aarch64";
      hash = "sha256-1RA5dRBPFS/VuqYebNyzBAn1/7oMaxMQ0OQWAdO8TGA=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.19/uv-nix-0.12.19-darwin-arm64";
      hash = "sha256-4WQjbbrkMTOH79sWDtbq8PlGLvKSVtmDSZ8crg0XINg=";
    };
  };
}
