# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.6-nix";
  tag = "0.12.6";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.6/uv-nix-0.12.6-linux-x86_64";
      hash = "sha256-h9BsOmn0t9lORlk1ccY35jfKXaoaNb9PXRLplN5p32s=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.6/uv-nix-0.12.6-linux-aarch64";
      hash = "sha256-hKzm5PpmTPrmygynEdkDN3lQnzcZnHb4c09qWYHziKE=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.6/uv-nix-0.12.6-darwin-arm64";
      hash = "sha256-A/cT7TnF+1Je+LMVaYQ2l/JLgq9iAC+fUzeM8Q7fGvs=";
    };
  };
}
