# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.2-nix";
  tag = "0.12.2";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.2/uv-nix-0.12.2-linux-x86_64";
      hash = "sha256-jFe0Q1tzYcjFJ/XAaOeRhOMgbtYDJszongKi8ymp+m8=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.2/uv-nix-0.12.2-linux-aarch64";
      hash = "sha256-qANkFVrSplEa7mL9MdstPt1/8/dancHpJkxD7ftjA9k=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.2/uv-nix-0.12.2-darwin-arm64";
      hash = "sha256-Qh6OsKGhpEZd2OS9knjS3650fa9kncIVD8p/YE0dLvU=";
    };
  };
}
