# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.5-nix";
  tag = "0.12.5";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.5/uv-nix-0.12.5-linux-x86_64";
      hash = "sha256-E8nYc1RXKX1jcFv2hVppOPdvEQv+JnGmJzL7k9zhNag=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.5/uv-nix-0.12.5-linux-aarch64";
      hash = "sha256-XfSxt5vKg43TYdDSoaAKACLkHyExxu0pVgJU2YcVFkI=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.5/uv-nix-0.12.5-darwin-arm64";
      hash = "sha256-fhXV+RD6IJAt8+1BBYclvckTFj4WExjL5PH8pgs1pNU=";
    };
  };
}
