# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.9-nix";
  tag = "0.12.9";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.9/uv-nix-0.12.9-linux-x86_64";
      hash = "sha256-QQGXWMBS82SmN/3sm899cPnIAEvLkmQkLiFWWpPdKwE=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.9/uv-nix-0.12.9-linux-aarch64";
      hash = "sha256-O3XdoN9cIG1U4t8O7SdRKJpb5ZJ9uG1y3RrwlhE/umA=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.9/uv-nix-0.12.9-darwin-arm64";
      hash = "sha256-sjHHgWq+oXOSsSqORfW+KtFpMNeQv6Ukx/jvqXmOpG8=";
    };
  };
}
