# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.10-nix";
  tag = "0.12.10";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.10/uv-nix-0.12.10-linux-x86_64";
      hash = "sha256-2H2aFeKvoPXHtqYEgnz26Mk7tcCrO2bEHP0vWGb2MBA=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.10/uv-nix-0.12.10-linux-aarch64";
      hash = "sha256-Nxku0rzZs3zUDKeykNTlWZH18321ibeCrk19h7Tm+Fo=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.10/uv-nix-0.12.10-darwin-arm64";
      hash = "sha256-QArYmUHgGYKjxRcQi+xRljWIEOsHs9F5dZylU8IR1DI=";
    };
  };
}
