# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.1-nix";
  tag = "0.12.1";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.1/uv-nix-0.12.1-linux-x86_64";
      hash = "sha256-he19AGpU2bAXmUjdV40VK4so/RYkAkN1BDEFc3rS5m8=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.1/uv-nix-0.12.1-linux-aarch64";
      hash = "sha256-F+wkhYL9T/0kydcCUrkmjzPxHOsaZxof41Mkhp3C0d8=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.1/uv-nix-0.12.1-darwin-arm64";
      hash = "sha256-nGi7dsL3b3WdF5uNSfLN+umw0hTHw3j9ifZhXJ+bVhM=";
    };
  };
}
