# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.18-nix";
  tag = "0.12.18";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.18/uv-nix-0.12.18-linux-x86_64";
      hash = "sha256-iqE6izRzvL/DKQ8pRpKJSpsH0Gdap9ZgJGGtiNAzac0=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.18/uv-nix-0.12.18-linux-aarch64";
      hash = "sha256-XEAwh8ip4MIBtSs8MmvFNpcSgbXY7mPy0t21QjyxyN8=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.18/uv-nix-0.12.18-darwin-arm64";
      hash = "sha256-CdL05c0KiQrHyIaPdSc+KuWcvOr91iO+VFihDdpGCDQ=";
    };
  };
}
