# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.15-nix";
  tag = "0.12.15";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.15/uv-nix-0.12.15-linux-x86_64";
      hash = "sha256-uDo3Em620T6FxfCBgiCIf5esm/Pd83sPrFDA/0n2wz0=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.15/uv-nix-0.12.15-linux-aarch64";
      hash = "sha256-WhLCO9NPxxCRKk0BTWNnfeuKE3mIQKaJx3Ym79gJ9+4=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.15/uv-nix-0.12.15-darwin-arm64";
      hash = "sha256-GzBiPprkmQFS8SWeBPC2adQnCXRthb62+K9woG8lQ0Q=";
    };
  };
}
