# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.12-nix";
  tag = "0.12.12";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.12/uv-nix-0.12.12-linux-x86_64";
      hash = "sha256-2odAjVaSGxDz52ckFoHK/xGx6+LO8zE9oewjtG4+mN0=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.12/uv-nix-0.12.12-linux-aarch64";
      hash = "sha256-k/wJqbPPJtrEvgmIarhmBOyFXCYDc1llNGzv2ZEUBEY=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.12/uv-nix-0.12.12-darwin-arm64";
      hash = "sha256-8Y45skR8mDcK+Vz3dSS8O2+9rSYIq6bUBix7HTmocjo=";
    };
  };
}
