# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.7-nix";
  tag = "0.12.7";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.7/uv-nix-0.12.7-linux-x86_64";
      hash = "sha256-5ZCmh2QToce6fTX+w46OW+Oz033BVq7kt4oyPEBLQB4=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.7/uv-nix-0.12.7-linux-aarch64";
      hash = "sha256-UzKm6BznXmaCao5GWV7mWm/Lbbcv8+R5++NLvIW4emk=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.7/uv-nix-0.12.7-darwin-arm64";
      hash = "sha256-R8pbK6OivX/cnGXp9E5fNc4vQWjRqH6WgLXKBrZUSY8=";
    };
  };
}
