# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.13-nix";
  tag = "0.12.13";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.13/uv-nix-0.12.13-linux-x86_64";
      hash = "sha256-Opop+dvwo8fnrL0y0MltCcJJ+sFZ9r9sNk4qbglvX60=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.13/uv-nix-0.12.13-linux-aarch64";
      hash = "sha256-c3a5jcNw1U8PZeeQu6oS3U4z/18TS8eZYYooL0fwF08=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.13/uv-nix-0.12.13-darwin-arm64";
      hash = "sha256-bM2U3wONBmFSL53Kahy8q/D/Oiy+WdVfp84zSbD4ctM=";
    };
  };
}
