# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.3-nix";
  tag = "0.12.3";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.3/uv-nix-0.12.3-linux-x86_64";
      hash = "sha256-XWPb9qxsf53Xi0YOsnQbb0CPMu1biQookte2XWD0v4I=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.3/uv-nix-0.12.3-linux-aarch64";
      hash = "sha256-54VKJT3bEBnQJMtyfoegyYnIwdCnrgF7WPkuQbl83sA=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.3/uv-nix-0.12.3-darwin-arm64";
      hash = "sha256-l4iplm3i/gdnlwjMyBsMvMcN8rj2V0e/I74zpbirmQo=";
    };
  };
}
