# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.23-nix";
  tag = "0.12.23";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.23/uv-nix-0.12.23-linux-x86_64";
      hash = "sha256-3/pTEfKIa5y5pPoR94QZfx4/A9CfftYZGtRhOHtc8tQ=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.23/uv-nix-0.12.23-linux-aarch64";
      hash = "sha256-oP6VoMqk793A7Bl1MK/yWPKsgpx6A1T2LpuEOywJ0fM=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.23/uv-nix-0.12.23-darwin-arm64";
      hash = "sha256-bcs3ChLot0KeFaxpLgbRNMjoVn8ENi6KQ06Dw494RtY=";
    };
  };
}
