# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.4-nix";
  tag = "0.12.4";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.4/uv-nix-0.12.4-linux-x86_64";
      hash = "sha256-6VxB8Mz1N8XCbzz60+DTRNYThbyN8K6BPqWOY6SJUO4=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.4/uv-nix-0.12.4-linux-aarch64";
      hash = "sha256-1OU2NHtmCkAhMAwOsW9uODh7TzN10kNUTliWIaWmCVM=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.4/uv-nix-0.12.4-darwin-arm64";
      hash = "sha256-5b3RZYdIt1ohS3XCRqzTRxTBPpbh0TWX0dqJGS9bS2I=";
    };
  };
}
