# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.20-nix";
  tag = "0.12.20";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.20/uv-nix-0.12.20-linux-x86_64";
      hash = "sha256-RX0HNqDeA1TGGc20+19lEYYYMU8uJChzyjgKD41PmLY=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.20/uv-nix-0.12.20-linux-aarch64";
      hash = "sha256-BVcXMO3652A9Qh0dlwktg81gfSxagtF8S6KZAIKe2i0=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.20/uv-nix-0.12.20-darwin-arm64";
      hash = "sha256-ojOfsJXCBjCUEWjZ497KrT1bDHaRBmWDXvhwmiJnJyI=";
    };
  };
}
