# Auto-generated by release workflow. Do not edit.
{
  version = "0.12.17-nix";
  tag = "0.12.17";
  assets = {
    "x86_64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.17/uv-nix-0.12.17-linux-x86_64";
      hash = "sha256-iBxIGBsyjCI1rKh+HEKl/Q27dIPTm77r6Cg37B5UrPs=";
    };
    "aarch64-linux" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.17/uv-nix-0.12.17-linux-aarch64";
      hash = "sha256-zadiOlEQSJOUVka51CkH5QBopHdPcOrS19auDdfA5Oc=";
    };
    "aarch64-darwin" = {
      url = "https://github.com/chadac/uv-nix/releases/download/0.12.17/uv-nix-0.12.17-darwin-arm64";
      hash = "sha256-nL5mV5x2s7MbY8BtwNlO8ro9iOJzkdJVK1KQ3dFAMnQ=";
    };
  };
}
