//! Nix expression generation from patch manifests.
//!
//! Reads `.venv/share/uv-nix/patches.json` (written by post-install patching)
//! and generates Nix expressions for use with uv2nix.
//!
//! Two output modes:
//! - Full `package.nix`: complete uv2nix derivation with workspace, overlays, and native lib overrides
//! - Overlay-only (`--overlay-only`): just the override overlay for native library dependencies

use std::collections::BTreeSet;
use std::fmt::Write;

use owo_colors::OwoColorize;

use crate::soname::PatchManifest;

/// Options for `uv nix gen`.
#[derive(Debug, Clone)]
pub struct GenOptions {
    /// Path to the virtual environment (default: .venv).
    pub venv: std::path::PathBuf,
    /// Output file path (default: stdout).
    pub output: Option<std::path::PathBuf>,
    /// Only generate the override overlay, not the full package.nix.
    pub overlay_only: bool,
    /// Prefer wheels over sdists (default: true).
    pub prefer_wheels: bool,
}

/// Per-package native library requirements, derived from patch manifest.
#[derive(Debug, Clone)]
struct PackageLibs {
    /// Normalized package name (e.g., "numpy").
    name: String,
    /// Deduplicated nixpkgs attribute paths needed by this package (e.g., ["openblas", "zlib"]).
    nix_attrs: BTreeSet<String>,
}

/// Load the patch manifest from a venv and extract per-package nixpkgs dependencies.
///
/// Returns a sorted list of packages that have native library requirements.
fn collect_package_libs(manifest: &PatchManifest) -> Vec<PackageLibs> {
    let mut result = Vec::new();

    for (pkg_name, pkg_info) in &manifest.packages {
        let mut nix_attrs = BTreeSet::new();

        for resolved in pkg_info.patches.values() {
            for attr in &resolved.nix_libs {
                // Filter out internal/extra attrs (those starting with '_')
                if !attr.starts_with('_') {
                    nix_attrs.insert(attr.clone());
                }
            }
        }

        if !nix_attrs.is_empty() {
            result.push(PackageLibs {
                name: pkg_name.clone(),
                nix_attrs,
            });
        }
    }

    result.sort_by(|a, b| a.name.cmp(&b.name));
    result
}

/// Generate the native library override overlay as a Nix expression string.
///
/// Output format:
/// ```nix
/// # Auto-generated by `uv nix gen`. Do not edit.
/// # Native library overrides for uv2nix packages.
/// { pkgs, lib, ... }:
/// final: prev: {
///   numpy = prev.numpy.overrideAttrs (old: {
///     buildInputs = (old.buildInputs or []) ++ [
///       pkgs.openblas
///     ];
///   });
/// }
/// ```
fn render_overlay(packages: &[PackageLibs]) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by `uv nix gen`. Do not edit.\n");
    out.push_str("# Native library overrides for uv2nix packages.\n");
    out.push_str("{ pkgs, lib, ... }:\n");
    out.push_str("final: prev: {\n");

    for pkg in packages {
        let attrs: Vec<&String> = pkg.nix_attrs.iter().collect();
        writeln!(
            out,
            "  {} = prev.{}.overrideAttrs (old: {{",
            pkg.name, pkg.name
        )
        .unwrap();
        out.push_str("    buildInputs = (old.buildInputs or []) ++ [\n");
        for attr in &attrs {
            writeln!(out, "      pkgs.{attr}").unwrap();
        }
        out.push_str("    ];\n");
        out.push_str("  });\n");
    }

    out.push_str("}\n");
    out
}

/// Generate a complete `package.nix` that includes the uv2nix workspace setup
/// and the native library overrides.
///
/// Output format:
/// ```nix
/// # Auto-generated by `uv nix gen`. Do not edit.
/// {
///   pkgs,
///   lib,
///   uv2nix,
///   pyproject-nix,
///   pyproject-build-systems,
///   python ? pkgs.python312,
///   ...
/// }:
/// let
///   workspace = uv2nix.lib.workspace.loadWorkspace { workspaceRoot = ./.; };
///   overlay = workspace.mkPyprojectOverlay { sourcePreference = "wheel"; };
///
///   # Native library overrides from uv-nix patch analysis
///   uvNixOverrides = final: prev: { ... };
///
///   pythonSet =
///     (pkgs.callPackage pyproject-nix.build.packages { inherit python; }).overrideScope
///       (lib.composeManyExtensions [
///         pyproject-build-systems.overlays.default
///         overlay
///         uvNixOverrides
///       ]);
/// in {
///   inherit pythonSet;
///   venv = pythonSet.mkVirtualEnv "app-env" workspace.deps.default;
/// }
/// ```
fn render_package_nix(packages: &[PackageLibs], prefer_wheels: bool) -> String {
    let mut out = String::new();
    out.push_str("# Auto-generated by `uv nix gen`. Do not edit.\n");
    out.push_str("{\n");
    out.push_str("  pkgs,\n");
    out.push_str("  lib,\n");
    out.push_str("  uv2nix,\n");
    out.push_str("  pyproject-nix,\n");
    out.push_str("  pyproject-build-systems,\n");
    out.push_str("  python ? pkgs.python312,\n");
    out.push_str("  ...\n");
    out.push_str("}:\n");
    out.push_str("let\n");
    out.push_str("  workspace = uv2nix.lib.workspace.loadWorkspace { workspaceRoot = ./.; };\n");
    let source_pref = if prefer_wheels { "wheel" } else { "sdist" };
    writeln!(
        out,
        "  overlay = workspace.mkPyprojectOverlay {{ sourcePreference = \"{source_pref}\"; }};"
    )
    .unwrap();
    out.push('\n');

    // Inline the native lib overlay
    out.push_str("  # Native library overrides from uv-nix patch analysis\n");
    out.push_str("  uvNixOverrides = final: prev: {\n");
    for pkg in packages {
        let attrs: Vec<&String> = pkg.nix_attrs.iter().collect();
        writeln!(
            out,
            "    {} = prev.{}.overrideAttrs (old: {{",
            pkg.name, pkg.name
        )
        .unwrap();
        out.push_str("      buildInputs = (old.buildInputs or []) ++ [\n");
        for attr in &attrs {
            writeln!(out, "        pkgs.{attr}").unwrap();
        }
        out.push_str("      ];\n");
        out.push_str("    });\n");
    }
    out.push_str("  };\n");
    out.push('\n');

    out.push_str("  pythonSet =\n");
    out.push_str(
        "    (pkgs.callPackage pyproject-nix.build.packages { inherit python; }).overrideScope\n",
    );
    out.push_str("      (lib.composeManyExtensions [\n");
    out.push_str("        pyproject-build-systems.overlays.default\n");
    out.push_str("        overlay\n");
    out.push_str("        uvNixOverrides\n");
    out.push_str("      ]);\n");
    out.push_str("in {\n");
    out.push_str("  inherit pythonSet;\n");
    out.push_str("  venv = pythonSet.mkVirtualEnv \"app-env\" workspace.deps.default;\n");
    out.push_str("}\n");
    out
}

/// Entry point for `uv nix gen`.
pub fn nix_gen<O: Write, E: Write>(
    out: &mut crate::cli::CliOutput<'_, O, E>,
    opts: GenOptions,
) -> anyhow::Result<()> {
    let venv_path = opts.venv.canonicalize().unwrap_or(opts.venv.clone());

    if !venv_path.exists() {
        anyhow::bail!("Virtual environment not found: {}", venv_path.display());
    }

    // Load the patch manifest
    let manifest = PatchManifest::load_or_default(&venv_path);
    if manifest.packages.is_empty() {
        anyhow::bail!(
            "No patch data found. Run `uv sync` first to install packages and generate patch data."
        );
    }

    // Extract per-package native lib requirements
    let packages = collect_package_libs(&manifest);

    // Generate the Nix expression
    let nix_expr = if opts.overlay_only {
        render_overlay(&packages)
    } else {
        render_package_nix(&packages, opts.prefer_wheels)
    };

    // Write output
    if let Some(ref output_path) = opts.output {
        std::fs::write(output_path, &nix_expr)?;
        let _ = writeln!(
            out.stderr,
            "{} {}",
            "Generated".green().bold(),
            output_path.display()
        );
    } else {
        let _ = write!(out.stdout, "{nix_expr}");
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::soname::{PackagePatchInfo, ResolvedBinary};
    use std::collections::BTreeMap;

    type PkgSpec<'a> = (&'a str, &'a str, Vec<(&'a str, Vec<&'a str>)>);

    /// Helper: build a PatchManifest from a list of (pkg_name, version, [(binary, [nix_libs])]).
    fn make_manifest(packages: Vec<PkgSpec<'_>>) -> PatchManifest {
        let mut pkgs = BTreeMap::new();
        for (name, version, binaries) in packages {
            let mut patches = BTreeMap::new();
            for (bin_path, libs) in binaries {
                patches.insert(
                    bin_path.to_string(),
                    ResolvedBinary {
                        needed: vec![],
                        nix_libs: libs.into_iter().map(|s| s.to_string()).collect(),
                        rpaths_added: vec![],
                    },
                );
            }
            pkgs.insert(
                name.to_string(),
                PackagePatchInfo {
                    version: version.to_string(),
                    patches,
                },
            );
        }
        PatchManifest {
            nixpkgs_rev: "abc123".to_string(),
            packages: pkgs,
        }
    }

    #[test]
    fn collect_package_libs_basic() {
        let manifest = make_manifest(vec![
            (
                "numpy",
                "1.26.0",
                vec![("numpy/core/_multiarray.so", vec!["openblas", "zlib"])],
            ),
            (
                "pandas",
                "2.1.0",
                vec![("pandas/_libs/lib.so", vec!["zlib"])],
            ),
        ]);
        let libs = collect_package_libs(&manifest);
        assert_eq!(libs.len(), 2);
        assert_eq!(libs[0].name, "numpy");
        assert_eq!(
            libs[0].nix_attrs,
            BTreeSet::from(["openblas".into(), "zlib".into()])
        );
        assert_eq!(libs[1].name, "pandas");
        assert_eq!(libs[1].nix_attrs, BTreeSet::from(["zlib".into()]));
    }

    #[test]
    fn collect_package_libs_deduplicates() {
        let manifest = make_manifest(vec![(
            "numpy",
            "1.26.0",
            vec![
                ("numpy/core/_multiarray.so", vec!["openblas", "zlib"]),
                ("numpy/linalg/_umath_linalg.so", vec!["openblas"]),
            ],
        )]);
        let libs = collect_package_libs(&manifest);
        assert_eq!(libs.len(), 1);
        assert_eq!(
            libs[0].nix_attrs,
            BTreeSet::from(["openblas".into(), "zlib".into()])
        );
    }

    #[test]
    fn collect_package_libs_filters_underscore_attrs() {
        let manifest = make_manifest(vec![(
            "foo",
            "1.0.0",
            vec![("foo/bar.so", vec!["zlib", "_internal_thing"])],
        )]);
        let libs = collect_package_libs(&manifest);
        assert_eq!(libs.len(), 1);
        assert_eq!(libs[0].nix_attrs, BTreeSet::from(["zlib".into()]));
    }

    #[test]
    fn collect_package_libs_skips_empty() {
        let manifest = make_manifest(vec![
            (
                "numpy",
                "1.26.0",
                vec![("numpy/core/_multiarray.so", vec!["openblas"])],
            ),
            ("pure-python", "1.0.0", vec![]),
        ]);
        let libs = collect_package_libs(&manifest);
        assert_eq!(libs.len(), 1);
        assert_eq!(libs[0].name, "numpy");
    }

    #[test]
    fn collect_package_libs_sorted() {
        let manifest = make_manifest(vec![
            ("zlib-wrapper", "1.0.0", vec![("z.so", vec!["zlib"])]),
            ("aaa-lib", "1.0.0", vec![("a.so", vec!["openssl"])]),
        ]);
        let libs = collect_package_libs(&manifest);
        assert_eq!(libs[0].name, "aaa-lib");
        assert_eq!(libs[1].name, "zlib-wrapper");
    }

    #[test]
    fn render_overlay_single_package() {
        let packages = vec![PackageLibs {
            name: "numpy".into(),
            nix_attrs: BTreeSet::from(["openblas".into()]),
        }];
        let output = render_overlay(&packages);
        assert!(output.contains("Auto-generated"));
        assert!(output.contains("final: prev:"));
        assert!(output.contains("numpy = prev.numpy.overrideAttrs"));
        assert!(output.contains("pkgs.openblas"));
    }

    #[test]
    fn render_overlay_multiple_packages() {
        let packages = vec![
            PackageLibs {
                name: "numpy".into(),
                nix_attrs: BTreeSet::from(["openblas".into(), "zlib".into()]),
            },
            PackageLibs {
                name: "pandas".into(),
                nix_attrs: BTreeSet::from(["zlib".into()]),
            },
        ];
        let output = render_overlay(&packages);
        assert!(output.contains("numpy = prev.numpy.overrideAttrs"));
        assert!(output.contains("pkgs.openblas"));
        assert!(output.contains("pkgs.zlib"));
        assert!(output.contains("pandas = prev.pandas.overrideAttrs"));
    }

    #[test]
    fn render_overlay_empty() {
        let output = render_overlay(&[]);
        assert!(output.contains("final: prev:"));
        // Should still be valid Nix (empty attrset)
    }

    #[test]
    fn render_package_nix_contains_uv2nix_boilerplate() {
        let packages = vec![PackageLibs {
            name: "numpy".into(),
            nix_attrs: BTreeSet::from(["openblas".into()]),
        }];
        let output = render_package_nix(&packages, true);
        assert!(output.contains("uv2nix"));
        assert!(output.contains("pyproject-nix"));
        assert!(output.contains("pyproject-build-systems"));
        assert!(output.contains("loadWorkspace"));
        assert!(output.contains("mkPyprojectOverlay"));
        assert!(output.contains("sourcePreference = \"wheel\""));
        assert!(output.contains("composeManyExtensions"));
        assert!(output.contains("mkVirtualEnv"));
        // The overlay should be inlined
        assert!(output.contains("numpy = prev.numpy.overrideAttrs"));
    }

    #[test]
    fn render_package_nix_prefer_sdist() {
        let output = render_package_nix(&[], false);
        assert!(output.contains("sourcePreference = \"sdist\""));
    }

    #[test]
    fn render_package_nix_empty_packages() {
        let output = render_package_nix(&[], true);
        // Even with no native libs, we should still get valid uv2nix boilerplate
        assert!(output.contains("uv2nix"));
        assert!(output.contains("mkVirtualEnv"));
    }

    #[test]
    fn nix_gen_missing_venv_errors() {
        let mut stdout = String::new();
        let mut stderr = String::new();
        let mut out = crate::cli::CliOutput {
            stdout: &mut stdout,
            stderr: &mut stderr,
        };
        let opts = GenOptions {
            venv: "/nonexistent/path/.venv".into(),
            output: None,
            overlay_only: false,
            prefer_wheels: true,
        };
        let result = nix_gen(&mut out, opts);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("not found"));
    }

    #[test]
    fn nix_gen_empty_manifest_errors() {
        let dir = tempfile::tempdir().unwrap();
        let venv = dir.path().join(".venv");
        std::fs::create_dir_all(venv.join("share/uv-nix")).unwrap();
        std::fs::write(
            venv.join("share/uv-nix/patches.json"),
            r#"{"nixpkgs_rev":"abc","packages":{}}"#,
        )
        .unwrap();

        let mut stdout = String::new();
        let mut stderr = String::new();
        let mut out = crate::cli::CliOutput {
            stdout: &mut stdout,
            stderr: &mut stderr,
        };
        let opts = GenOptions {
            venv,
            output: None,
            overlay_only: false,
            prefer_wheels: true,
        };
        let result = nix_gen(&mut out, opts);
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("No patch data"));
    }
}
